apiVersion: v1
kind: Service
metadata:
  name: transaction-api-service
  labels:
    app: transaction-api
spec:
  selector:
    app: transaction-api
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: NodePort
