name: CI CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out source code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.20"

    - name: Install dependencies
      run: go mod tidy

    - name: Build
      run: go build -o transaction-api ./api/

    - name: Run tests
      run: go test ./api/...

    - name: Build Docker image
      run: docker build -t your-docker-registry/transaction-api:latest -f build/Dockerfile.api .

    - name: Log into Docker registry
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push Docker image
      run: docker push your-docker-registry/transaction-api:latest

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: "latest"

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deploy/postgres-configmap.yaml
        kubectl apply -f deploy/postgres-deployment.yaml
        kubectl apply -f deploy/postgres-service.yaml
        kubectl apply -f deploy/api-deployment.yaml
        kubectl apply -f deploy/api-service.yaml
